#!/usr/bin/env bash
git-subtree add -P application git@github.com:jonathanmarvens/jonathanmarvens.com.git master
# git-subtree add -P content/public/resources/twitter/bootstrap git@github.com:jonathanmarvens/twitter-bootstrap.git master