#!/usr/bin/env bash
git subtree push -P application git@github.com:jonathanmarvens/jonathanmarvens.com.git master
git subtree push -P application/static/public/resources/twitter/bootstrap git@github.com:jonathanmarvens/twitter-bootstrap.git master