// Generated by CoffeeScript 1.3.3
var displayLatestGitHubCommits;

displayLatestGitHubCommits = function() {
  var github_commits;
  github_commits = new $_GitHub_LC({
    'callback': function(data) {
      $('span.home-github-commits-loading').html('Please wait while the GitHub commits are loaded.');
      $.each(data, function(key, value) {
        var html_data;
        html_data = '<dt>' + '<a href="' + value.repo['html_url'] + '">' + value.repo['name'] + '</a>' + '</dt>' + '<dd>' + '<small>';
        $.each(value.commits, function(commit_key, commit_value) {
          return html_data += '<code>&#64;' + commit_value['committer']['login'] + '</code> ' + '<i class="icon-arrow-right"></i> ' + '<code>' + commit_value['sha'].slice(0, 10) + '</code> ' + '<span class="boldify">with</span> ' + '<code>' + commit_value['commit']['message'] + '</code> ' + '<br>';
        });
        html_data += '</small>';
        html_data += '</dd>' + '<hr>';
        if (key === 0) {
          $('dl#home-latest-github-commits').html(html_data);
        } else {
          $('dl#home-latest-github-commits').append(html_data);
        }
      });
    },
    'commit_count': 5,
    'debug': 0,
    'repo_count': 3,
    'user': 'jonathanmarvens'
  }).run();
};

$(document).ready(function() {
  displayLatestGitHubCommits();
});
